import os
import requests
import json
from dotenv import load_dotenv

# Load environment variables
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(PROJECT_ROOT, ".env"))

serper_key = os.getenv("SERPER_API_KEY")

query = 'site:linkedin.com/posts "looking for" "corporate lawyer"'
headers = {
    "X-API-KEY": serper_key,
    "Content-Type": "application/json"
}

# 1. Try with num=10
print("--- Requesting with num=10 ---")
payload_10 = {"q": query, "num": 10}
resp = requests.post("https://google.serper.dev/search", headers=headers, json=payload_10)
print(f"Status Code: {resp.status_code}")
if resp.status_code == 200:
    results = resp.json().get("organic", [])
    print(f"Total results: {len(results)}")
    for i, item in enumerate(results[:5], 1):
        print(f"  {i}. Link: {item.get('link')}\n     Title: {item.get('title')}\n     Snippet: {item.get('snippet')}")
else:
    print(f"Response: {resp.text}")

# 2. Try with fallback queries
print("\n--- Requesting with intent queries generated by app ---")
from search.query_generator import IntentQueryGenerator
intent_queries = IntentQueryGenerator.generate("looking for corporate lawyer")
print(f"Generated Intent Queries: {intent_queries}")
for iq in intent_queries:
    full_q = f"site:linkedin.com/posts {iq}"
    print(f"Testing full query: {full_q}")
    payload = {"q": full_q, "num": 10}
    resp = requests.post("https://google.serper.dev/search", headers=headers, json=payload)
    print(f"Status Code: {resp.status_code}")
    if resp.status_code == 200:
        results = resp.json().get("organic", [])
        print(f"Total results: {len(results)}")
        for idx, item in enumerate(results[:5], 1):
            print(f"  {idx}. Link: {item.get('link')}\n     Title: {item.get('title')}\n     Snippet: {item.get('snippet')}")
    else:
        print(f"Response: {resp.text}")
